/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c57d7066592cca638bc20b8192065140)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "InboxAgent";
	}
	interface Env {
		EMAIL: SendEmail;
		AI: Ai;
		InboxAgent: DurableObjectNamespace<import("./src/server").InboxAgent>;
	}
}
interface Env extends Cloudflare.Env {}
